### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by kmanwar** [Deeptiman/Alphabet-Learning-Android-Application#1]
After building the app it was crashing after loading the updates..

**Comment by Deeptiman** [comment]
@kmanwar What error log you are getting? please share log

**Comment by Jyoti-Chakma** [comment]
![Screenshot_2020-09-28-20-20-47-974_com awesun control](https://user-images.githubusercontent.com/64517053/94445040-cf6c4b80-01c8-11eb-9f18-5137ddcc16e9.jpg)
It shows [error: resources android:attr/dialogCornerRadius not found]
4 errors exist of same types.

**Comment by Jyoti-Chakma** [comment]
![IMG_20200928_202850](https://user-images.githubusercontent.com/64517053/94445426-3db10e00-01c9-11eb-8e68-d4f5ae411ee6.jpg)
It shows [error: resources android:attr/dialogCornerRadius not found]
4 error exists of same types.

**Comment by Deeptiman** [comment]
@Jyoti-Chakma Please delete your .gradle folder to clear the existing cache. Then try building again.

**Comment by Jyoti-Chakma** [comment]
> @Jyoti-Chakma Please delete your .gradle folder to clear the existing cache. Then try building again.

@Deeptiman , I have deleted the .gradle folder and rebuild the project. But the errors still exist.

**Comment by Deeptiman** [comment]
@Jyoti-Chakma Please do Clean Project, Delete the app build folder and then try. You may have a few caches that creating the build failed.

**Comment by Jyoti-Chakma** [comment]
@Deeptiman  Thank you. It's compiled. But the touch response seems to be a bit slow. How can I get a smooth touch response?

**Comment by Deeptiman** [comment]
@Jyoti-Chakma The touch response depends on the device, which device you are having? Please also check with the source code review and let me know if you find anything interesting to optimize.

I am closing this issue for now.
